[model]
model = "gpt-4o-mini"

[environment]
type = "dev"

[timeout]
llm = 60

# 1. News Aggregator Agent

[News_Aggregator_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are a news aggregator agent. Your role is to gather the latest news from the defined API.
"""
tools = [
    { module = "app.tools", name = "fetch_news" }
]


# 2. Audio Narration Generator Agent
[Audio_Narration_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are an audio narration generator agent. Your role is to convert the summarized text for each news story from 'News_Aggregator_Agent' into audio.
"""
tools = [
    { module = "app.tools", name = "text_to_speech" }
]

# 3. Script Writing Agent for Visuals
[Script_Writer_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are a script writer agent.
Based on the summarized audio for the top news stories, write a short visual script.
Each news story should have **1-2 accompanying images**.
"""

# 4. Scene Prompt and Image Generation

[Scene_Prompt_Generator_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are a scene prompt generator agent. For each news summary, create detailed image prompts to generate visuals relevant to the content.
Ensure that each news story has **1-2 images** that align with the summarized audio.
"""

[Scene_Image_Generator_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are a scene image generator agent. Use the prompts from the Scene Prompt Generator Agent to generate the images for each news summary.
Return the URLs of the generated images.
"""

tools = [
    { module = "app.tools", name = "text_to_image" }
]

# 5. Video Creation: Scene to Video

[Scene_Image_to_Video_Generator_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are a scene image to video generator agent.
Use the images generated by the Scene Image Generator Agent to create short video segments for each news summary.
Ensure each segment aligns with the audio narration.
"""

tools = [
    { module = "app.tools", name = "image_to_video" }
]

# 6. Video Editor

[Video_Editor_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are a video editor agent. Combine the audio narration and video segments to create the final video.
Ensure smooth transitions between news stories and proper alignment of audio with visuals.
"""

tools = [
    { module = "app.tools", name = "video_editor" }
]

# 7. YouTube Upload for POC

[Youtube_Upload_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are a youtube upload agent on a video production team.
You should use the videos from the video editor agent and upload them to youtube.
You should also create a title, description and keywords for the video.
"""

tools = [
    { module = "app.tools", name = "upload_video" }
]
