[model]
model = "gpt-4o-mini"

[environment]
type = "dev"

[timeout]
llm = 60

# 1. News Aggregator Agent

[News_Aggregator_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are a news aggregator agent. Your role is to gather the latest news from APIs.
Limit the collection to the **top 3 relevant news stories**.
"""

tools = [
    { module = "app.tools", name = "news_api_fetcher" }
]

# 2. News Analyzer and Summarizer Agent

[News_Analyzer_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are a news analysis and summarizer agent.
After gathering the top 3 news stories, summarize each one in a concise and engaging manner.
Each summary should be around **5-6 seconds** in duration to fit within the 10-second news segment.
"""

# 3. Audio Narration Generator Agent

[Audio_Narration_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are an audio narration generator agent. Your role is to convert the summarized text for each news story into audio.
Ensure the narration is clear, professional, and fits within the **5-6 second** length per news story.
"""

tools = [
    { module = "app.tools", name = "text_to_speech" }
]

# 4. Script Writing Agent for Visuals

[Script_Writer_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are a script writer agent.
Based on the summarized audio for the top 3 news stories, write a short visual script.
Each news story should have **1-2 accompanying images**, with each shown for around **3-5 seconds**.
"""

# 5. Scene Prompt and Image Generation

[Scene_Prompt_Generator_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are a scene prompt generator agent. For each news summary, create detailed image prompts to generate visuals relevant to the content.
Ensure that each news story has **1-2 images** that align with the summarized audio.
"""

[Scene_Image_Generator_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are a scene image generator agent. Use the prompts from the Scene Prompt Generator Agent to generate the images for each news summary.
Return the URLs of the generated images.
"""

tools = [
    { module = "app.tools", name = "text_to_image" }
]

# 6. Video Creation: Scene to Video

[Scene_Image_to_Video_Generator_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are a scene image to video generator agent.
Use the images generated by the Scene Image Generator Agent to create short video segments for each news summary.
Ensure each segment aligns with the audio narration and lasts **5-7 seconds**.
"""

tools = [
    { module = "app.tools", name = "image_to_video" }
]

# 7. Video Editor: Final Video Under 30 Seconds

[Video_Editor_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are a video editor agent. Combine the audio narration and video segments to create the final video, ensuring it does not exceed **30 seconds** in total length.
Ensure smooth transitions between news stories and proper alignment of audio with visuals.
"""

tools = [
    { module = "app.tools", name = "video_editor" }
]

# 8. YouTube Upload for POC

[Youtube_Upload_Agent]
model = "gpt-4o-mini"
environment = "dev"
timeout = 60
instruction = """
You are a youtube upload agent on a video production team.
You should use the videos from the video editor agent and upload them to youtube.
You should also create a title, description and keywords for the video.
"""

tools = [
    { module = "app.tools", name = "upload_video" }
]
